### ISSUE TITLE
Get human-readable EXIF tag description

### ISSUE THREAD

**Issue by ganego** [LeoHsiao1/pyexiv2#10]
I'm looking for some Python EXIF solution that can handle "MakerNote", so I had to find some exiv2-based solution, one of them is yours.

Is it possible to get the "tag description" via the exiv2 library and your wrapper?
Example: https://www.exiv2.org/tags-canon.html. I can get `Exif.Canon.ShotInfo` but I also want the string `Shot information` which is from the "tag description" column.

exiv2 seems to support it:
https://github.com/Exiv2/exiv2/blob/master/src/canonmn_int.cpp#L427  
With probably this:  
https://github.com/Exiv2/exiv2/blob/master/include/exiv2/tags.hpp#L207 (tagDesc)

Thank you

**Comment by LeoHsiao1** [comment]
Hi!
I found that pyexiv2 can't edit the two tags you said:
```python
>>> img.modify_exif({'Exif.Photo.MakerNote': 'test', 'Exif.Canon.ShotInfo': 'test'})  
>>> img.read_exif()['Exif.Photo.MakerNote'] 
''
>>> img.read_exif()['Exif.Canon.ShotInfo']  
''
```

I'm calling exiv2's API just like the [example](https://github.com/Exiv2/exiv2/blob/d4d4d766e9ade2376115eb41cc478eb195df1b39/samples/exifprint.cpp#L84), but I don't know how to read `tag description`.
If you find that API, I can add it to pyexiv2.
