### ISSUE TITLE
Source not available after 2.5.0

### ISSUE THREAD

**Issue by guilhermef** [LeoHsiao1/pyexiv2#103]
Hi @LeoHsiao1, I've been having some issues when trying to install the latest version on Mac M1.
The source isn't available in Pypi, only the wheels and there's no wheel for Mac M1.

Can you release also the package in `.tar.gz`?

Thanks.

**Comment by guilhermef** [comment]
@LeoHsiao1 I've been using QEmu to compile for ARM on other projects: https://github.com/uraimo/run-on-arch-action
It works well.

**Comment by guilhermef** [comment]
I also have this PR on the Thumbor project, that compiles to multiple architectures https://github.com/thumbor/thumbor/pull/1498/files using `cibuildwheel`

**Comment by LeoHsiao1** [comment]
Thanks for your advice.
I learned about `uraimo/run-on-arch-action@v2` in the evening. It seems like it only supports Ubuntu, not MacOS.
I'm not familiar with the arm and aarch64 architectures. Can we cross-compile them on the amd64 machine provided by GitHub action?

cibuildwheel supports cross-compilation. But it relies on `python setup.py` to build, requiring C++ compilation commands to be converted into Python code. It looks tricky.
Also, I searched for GitLab Runner, Travis CI and CircleCI. But none of them offer free MacOS Arm machines.

**Comment by guilhermef** [comment]
According to this page, it's possible to cross-compile for Arm on Mac: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by LeoHsiao1** [comment]
Good morning.
I learned that cross-compiling is possible. So I tried to build, and the first challenge I found was how to build exiv2. There are some C++ code compatibility problems that I couldn't solve.
The good news is that this PR <https://github.com/Exiv2/exiv2/pull/1235> tries to build exiv2 on arm machines. But the work is not yet done.

**Comment by LeoHsiao1** [comment]
Currently, exiv2 only supports compilation on amd64 platform. Compilations on other platforms may work, but there is no documentation.
pyexiv2 also has this limitation.
