### ISSUE TITLE
Hi i am search for adding XMP tags to IPTC  is it possible by any means ?

### ISSUE THREAD

**Issue by faridelya** [LeoHsiao1/pyexiv2#111]
Hi, Hope you doing well.
I have used Exiftool but it adds only predefined tags in each standard of metadata  like XMP and IPTC 

if both standards share a common tag name then we can also add this but I want to add all xmp tags to iptc and all iptc tag to xmp  or we can say custom tag for IPTC or XMP 

I also used exic2 c++   n ubuntu command line but I was not able to add this 
if we can then how if not then why what is the disadvantage of adding a custom tag?

Thanks

**Comment by LeoHsiao1** [comment]
Yes, you can write an unlimited number of custom tags.‘
For example:
```py
>>> img.modify_xmp({'Xmp.dc.mytag1': 'Hello'})
>>> img.read_xmp()['Xmp.dc.mytag1']
'Hello'
```
Please see https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md#modify

**Comment by LeoHsiao1** [comment]
I have tried, exiv2 can only write custom XMP tags, not EXIF, IPTC.
