### ISSUE TITLE
Python 3.12 wheels missing and no source release on PyPI

### ISSUE THREAD

**Issue by Tenzer** [LeoHsiao1/pyexiv2#121]
Python 3.12 was [released](https://pythoninsider.blogspot.com/2023/10/python-3120-final-now-available.html) last week and I've been working on upgrading our services to use it.

One of the services uses this library as a dependency, but it isn't possible to install it on Python 3.12 because there's no wheel available for Python 3.12. Also, curiously, there's no source distribution available on PyPI either: https://pypi.org/project/pyexiv2/#files. I guess that means the only possible way to install this library on Python 3.12 would be to point at this Git repository?

Would it be possible to get wheels created for Python 3.12 and uploaded to PyPI, and possibly also a source distribution, please?

**Comment by LeoHsiao1** [comment]
Aha, it's only been a week since python12 was released, you're quite industrious.
I'm sorry to keep you waiting, so I've just released [v2.8.3](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.8.3)

**Comment by LeoHsiao1** [comment]
Well, pyexiv2 is a python library compiled from C++ code.
The compilation tool is pybind11, which is incompatible with every python subversion. So, I need to compile it once for each python subversion.
