### ISSUE TITLE
How to catch "bad metadata" vs no metadata

### ISSUE THREAD

**Issue by fire-eggs** [LeoHsiao1/pyexiv2#123]
I have some images which have invalid metadata. I need to be able to distinguish between:
1. An image which has invalid metadata
2. An image which doesn't have a particular metadata key
3. An image which does have a particular metadata key
4. A file path which is not a valid image

How might I do this using pyexiv2?

Thank you!

**Comment by LeoHsiao1** [comment]
Hi
pyexiv2 can accomplish these four tasks. But its answer may be different from other software.
There are popular specifications about image metadata, such as EXIF, IPTC, XMP. But not all companies' software strictly adheres to these specifications.
For example: pyexiv2 thinks that an image's metadata has a formatting error and cannot be parsed. But another program can parse the metadata.
In summary, if you need to be strict about determining whether metadata is valid or not, then you need to delve into the metadata specification or even write your own code.

**Comment by fire-eggs** [comment]
Thank you for the samples!
