### ISSUE TITLE
Support conversion

### ISSUE THREAD

**Issue by frafra** [LeoHsiao1/pyexiv2#129]
It would be nice to have these functions exposed: https://exiv2.org/doc/convert_8hpp.html.

**Comment by LeoHsiao1** [comment]
Hi!
I haven't used this feature in exiv2, I'll try it this week.

I'm going to add four functions:
```py
convert_exif_to_xmp(data:dict) -> dict
convert_iptc_to_xmp(data:dict) -> dict
convert_xmp_to_exif(data:dict) -> dict
convert_xmp_to_iptc(data:dict) -> dict
```
Expected results:
```py
>>> import pyexiv2
>>> pyexiv2.convert_exif_to_xmp({'Exif...': '...'})
{'Xmp...': '...'}
```

**Comment by LeoHsiao1** [comment]
I just release [v2.11.0](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.11.0)
