### ISSUE TITLE
After update from 2.12. to 2.14.: exception 0xC0000005 in modify_xmp

### ISSUE THREAD

**Issue by RalfPeter** [LeoHsiao1/pyexiv2#143]
I used version 2.12. of (your excellent) pyexiv2 package in python 3.11. Until now i didnt have any problems. 
After updating to version 2.14 i get an exception in pyexiv2.core.Image.modify_xmp when trying to update an image with data:
tag='Xmp. exif. DateTimeOriginal', value='2024:07:07 10:07:32+02:00'
I tried other xmp tags, i always get an exception. Only for updating xmp tags. All other (taht i use) seems to work fine.

Is there any change that i am missing?

**Comment by LeoHsiao1** [comment]
Hi!
It's just a normal tag, I can modify it, like this:
```py
>>> d = {'Xmp.exif.DateTimeOriginal': '2024:07:07 10:07:32+02:00'}
>>> img.modify_xmp(d)
>>> img.read_xmp()['Xmp.exif.DateTimeOriginal']
'2024:07:07 10:07:32+02:00'
```

You can also try to modify the image with `img.read_raw_xmp()` and `img.modify_raw_xmp()`.

Rather than suspecting a problem with exiv2, it's more likely that your image is special.
Would you be willing to share the image in a zip file?

**Comment by RalfPeter** [comment]
[2024-05-12 - Niederrhein (176) - Kraftwerkerunde mit Grace.zip](https://github.com/user-attachments/files/16561498/2024-05-12.-.Niederrhein.176.-.Kraftwerkerunde.mit.Grace.zip)

The image is a screenshot taken from chrome, saved as jpeg with pillow (Image.open(png_file).save(jpg_file, "JPEG")), the html file was generated with folium. 
As i mentioned before with pyexiv2 v. 2.12 the same sourcecode works, with the same image with the same python version (3.11 and 3.12). When i update my python installation to pyexiv2 v. 2.14. the error occurs.

**Comment by LeoHsiao1** [comment]
Thanks for the background information.
I downloaded the image and quickly modified it with Python 3.11 on a Windows 11 machine.
```py
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyexiv2
>>> pyexiv2.__version__
'2.14.0'
>>> path = r"d:\Desktop\2024-05-12 - Niederrhein (176) - Kraftwerkerunde mit Grace.jpg"
>>> img = pyexiv2.Image(path)
>>> img.read_xmp()['Xmp.exif.DateTimeOriginal']
'2024:05:12 11:49:02+02:00'
>>> d = {'Xmp.exif.DateTimeOriginal': '2024:07:07 10:07:32+02:00'}
>>> img.modify_xmp(d)
>>> img.read_xmp()['Xmp.exif.DateTimeOriginal']
'2024:07:07 10:07:32+02:00'
```

I also tried Python 3.10 on a Linux machine, and that was fine too.

pyexiv2 2.14 did not change the `modify_xmp()` API. So there shouldn't be a difference with pyexiv2 2.12 .
Maybe `0xC0000005` is a Windows compatibility issue. But I wouldn't dare speculate.

**Comment by RalfPeter** [comment]
Ok, i send you more of my code:

    # ---------------------------------------------------------------------------------------
    # set the exif creationdate and the exif author of a file
    # ---------------------------------------------------------------------------------------
    def write_creationdate(self, creation_date: datetime, creation_author='', rename: bool = False) -> bool:
        if creation_date is None:
            return False

        # Ändere die EXIF und IPTC-Daten des Bildes
        change_data_exif = {}
        change_data_iptc = {}
        change_data_xmp = {}

        if self.image:
            timezone_offset_hours = timezone_to_int(creation_date)
            timezone_string = timezone_to_str(creation_date)

            # Speichere aktualisierte Datumsfelder für exif und iptc
            change_data_exif[ExifDateTimeOriginal] = creation_date.strftime(EXIF_DATETIME_STR_FORMAT)
            change_data_exif[ExifDateTimeDigitized] = change_data_exif[ExifDateTimeOriginal]
            change_data_iptc[IPTCDateCreated] = creation_date.strftime(IPTC_DATE_STR_FORMAT)

            # Speichere passende Zeitzonen für exif und iptc
            if timezone_offset_hours > 0:
                change_data_exif[ExifTimezoneOffset] = timezone_offset_hours
            if timezone_string:
                change_data_exif[ExifOffsetTimeOriginal] = timezone_string
                change_data_exif[ExifOffsetTime] = timezone_string
                change_data_iptc[IPTCTimeCreated] = creation_date.strftime(IPTC_TIME_STR_FORMAT) + timezone_string
                change_data_xmp[XMPExifDateTimeOriginal] = change_data_exif[ExifDateTimeOriginal] + timezone_string
                change_data_xmp[XMPExifDateTimeDigitized] = change_data_xmp[XMPExifDateTimeOriginal]
            else:
                change_data_iptc[IPTCTimeCreated] = creation_date.strftime(IPTC_TIME_STR_FORMAT)
                change_data_xmp[XMPExifDateTimeOriginal] = change_data_exif[ExifDateTimeOriginal]
                change_data_xmp[XMPExifDateTimeDigitized] = change_data_xmp[XMPExifDateTimeOriginal]

            if creation_author:
                change_data_exif[ExifArtist] = creation_author
                change_data_iptc[IPTCByline] = creation_author

            if self.verbose:
                log(f"CreationDate [{creation_date}] und Author [{creation_author}] gesetzt.")

            self.update(change_exif=change_data_exif, change_iptc=change_data_iptc, change_xmp=change_data_xmp)

            if rename:
                self.rename_file(creation_date)

            return True

    # ---------------------------------------------------------------------------------------
    def update(self, change_exif: dict = None, change_iptc: dict = None, change_xmp: dict = None) -> bool:

        modified = False
        try:
            if change_exif:
                if len(change_exif) > 0:
                    self.image.modify_exif(change_exif)
                    self.data_exif = self.image.read_exif()
                    modified = True
            if change_iptc:
                if len(change_iptc) > 0:
                    self.image.modify_iptc(change_iptc)
                    self.data_iptc = self.image.read_iptc()
                    modified = True
            if change_xmp:
                if len(change_xmp) > 0:
                    self.image.modify_xmp(change_xmp)
                    self.data_xmp = self.image.read_xmp()
                    modified = True
        except AttributeError as e:
            if self.verbose:
                log('EXIF_init', f"Fehler: {type(e).__name__} - {e.args}")
            raise AttributeError

        return modified

In __init__ i do the following:
        # initialize image
        try:
            set_log_level(level=3)
            with open(self.file, 'rb') as f:
                self.image = ImageData(f.read())
                if self.image:
                    # Lese die Exif-Metadaten
                    self.data_exif = self.read_exif()
                    # Lese die IPTC-Metadaten
                    self.data_iptc = self.read_iptc()
                    # Lese die XMP-Metadaten
                    self.data_xmp = self.read_xmp()
                    # Lese den Kommentar
                    self.comment = self.image.read_comment()
                    # Lese die ICC-Metadaten
                    self.data_icc = self.image.read_icc()
                    # Lese die Thumbnail
                    self.data_thumbnail = self.image.read_thumbnail()
        except TypeError as e:
            if self.verbose:
                log('EXIF_init', f"Fehler: {type(e).__name__} - {e.args}")
            raise TypeError


Does this help? Am i doing something wrong? 

![2024-07-07 - Niederlande (146) - Wassenberg,Herkenbosch,Jülich,Elsdorf (Grace, Ralf)](https://github.com/user-attachments/assets/6246f47e-fca4-430d-8715-b33a224d1139)
This image is created from the screenshot and does not have any exif, iptc or xmp tags at all. Maybe this is the problem (empty xmp data?)

**Comment by LeoHsiao1** [comment]
Your operation is normal and there should be no error.
I tested it with a different Windows machine and guessed it was a Windows compatibility issue.
As you know, exiv2 is a software written in C++ and requires a C++ runtime environment.
Please download the latest version of `Microsoft Visual C++ Redistributable for Visual Studio 2022` from this page <https://visualstudio.microsoft.com/downloads/>

**Comment by RalfPeter** [comment]
I reinstalled latest VC redistributable (MSV C++ 14.40.33810). But nothing changed. I will try an easier sample. Still get a 0xC0000005.

**Comment by RalfPeter** [comment]
This are the installed python packages:
![packages](https://github.com/user-attachments/assets/26e31a58-cb35-4277-b964-969560c0f633)
And the error message:
![image](https://github.com/user-attachments/assets/ea1a390b-2a3b-492c-a7b2-6a831e05d6a7)
And here the coding:

`# This is a sample Python script.
import pyexiv2


def add_xmp():
    # Use a breakpoint in the code line below to debug your script.
    path = r"c:\users\Ralf\Desktop\2024-05-12 - Niederrhein (176) - Kraftwerkerunde mit Grace.jpg"
    img = pyexiv2.Image(path)
    # exif, iptc and xmp are empty!
    # mm = img.read_xmp()['Xmp.exif.DateTimeOriginal']
    # print('Vorher: %s' % mm)
    # Exif
    d = {'Exif.Photo.DateTimeOriginal': '2024:07:07 10:07:32+02:00'}
    img.modify_exif(d)
    mm = img.read_exif()['Exif.Photo.DateTimeOriginal']
    print('Exif: %s' % mm)
    # Xmp
    d = {'Xmp.exif.DateTimeOriginal': '2024:07:07 10:07:32+02:00'}
    img.modify_xmp(d)
    # Crash! with 14.2.0
    mm = img.read_xmp()['Xmp.exif.DateTimeOriginal']
    print('Xmp: %s' % mm)


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    add_xmp()
`



Addind exif data is ok, adding xmp data crashes. Do you have any other idea?

**Comment by LeoHsiao1** [comment]
Since you can use `pyexiv2==2.12`, but using `pyexiv2==2.14` will report an error. I'm still guessing it's a Windows compatibility issue.
I tried modifying xmp with pyexiv2 on multiple Windows computers. Some computers work fine, others crash the Python interpreter.
On the crashed computer, after I upgraded MSV C++, it modifies xmp correctly.

Now I can open your image and modify xmp on all Windows computers without any problems.
Since I can't reproduce your problem, I can't troubleshoot it further.

I'm sorry I didn't solve your problem.

**Comment by RalfPeter** [comment]
Ok, can you give me the version of your MS VC++? And perhaps the whole link to the download file? As i mentioned before, i have MSV C++ 14.40.33810 installed on my windows 11 machine (as well as some other versions 9.0, 10.0, 12.0, i guess some older programms need them).

**Comment by LeoHsiao1** [comment]
`pyexiv2==2.14` was built in July 2024 with the following build dependencies:
```py
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.37
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

I guess, pyexiv2 relies on the C++ runtime environment released after July 2024.
On my crashed computer, I found it installed `Microsoft Visual C++ 2015-2019 Redistributable(x86) - 14.29.30038`. After I installed `Microsoft Visual C++ 2015-2022 Redistributable(x64) - 14.40.33810`, pyexiv2 doesn't crash.

If this still doesn't solve your problem, there are other choices:
- Use `pyexiv2==2.12` instead of `pyexiv2==2.14`.
- Try `pyexiv2==2.14` with a new Windows computer.
- Install visual studio 2019 and compile `pyexiv2==2.14` manually. See [pyexiv2/lib](https://github.com/LeoHsiao1/pyexiv2/tree/master/pyexiv2/lib). But it will take you hours.

**Comment by RalfPeter** [comment]
Thank you for your answer. I tried the following: i deinstalled ALL MC VC++ runtime packages and pyexiv2 is still working. So if it relays on MS VC++ runtime, i must have installed it on my machine in a secret place.

**Comment by RalfPeter** [comment]
So, finally i found a solution:
- i deinstalled all runtime version of MS VC++ (including newest)
- i searched for exiv2.dll in all folders of my machine (found an older one in c:/windows/system32/) and deleted them
- in the system folder (c:/windows/system32) i found a MS VC++ 14.29.30038
- reinstalled the MS VC++ (with VC_redist.x64.exe from MS)
- now i have a MS VC++ in c:/windows/system32 with version 14.40.33810
Now all seems fine and the python did not crash any more

**Comment by LeoHsiao1** [comment]
Unbelievable! You fixed such a hidden bug!
Although the bug took us a few days, it got a happy ending.

**Comment by RalfPeter** [comment]
I hope that will help other users too. Thank you for your patience and help.
