### ISSUE TITLE
Permission Denied error when modifying exif

### ISSUE THREAD

**Issue by JoeWise** [LeoHsiao1/pyexiv2#144]
I'm trying to modify the exif data of an image, but keep getting a permission denied error.

Running the following code
```
import pyexiv2

img = pyexiv2.Image("Path\\To\\Image.JPG")
data = img.read_exif() # I am able to successfully read exif data in.
print(data["Exif.Photo.ExposureTime"])
img.modify_exif({'Exif.Photo.ExposureTime': '1/8'})
img.close()
```

I get the error
```
Traceback (most recent call last):
  File "D:\exiv2test.py", line 6, in <module>
  File "C:\Users\UserName\AppData\Roaming\Python\Python312\site-packages\pyexiv2\core.py", line 108, in modify_exif
    self._exiv2api_image.modify_exif(_dumps(data), encoding)
RuntimeError:Path\To\Image.JPG: Failed to open file (w+b): Permission denied (errno = 13)
```

I'm running Python 3.12.5 and pyexiv2 version 2.14.0 on Windows 11. 
Opening the image Properties window and looking at the Security tab, I have "Full Control" and all other permissions turned on. 
I have tried running the script from from a command prompt and powershell window run as an administrator, but still get this error.
I have also tried restarting the computer and running the script without opening any other programs to make sure that the file wasn't open in another program.

Any help is much appreciated!

**Comment by LeoHsiao1** [comment]
Hi!
This is an error about file permissions.
Windows often disables the modification of files on the C drive.

I can reproduce the error like this:
```py
>>> import pyexiv2
>>> path = r'c:\1.jpg'
>>> img = pyexiv2.Image(path)
>>> len(img.read_exif())
10
>>> img.modify_exif({'Exif.Photo.ExposureTime': '1/8'})
RuntimeError: c:\1.jpg: Failed to open file (w+b): Permission denied (errno = 13)
```

The solutions are as follows:
- Put the file in a directory that you have the right to modify, such as `'c:\Users\Username\Documents\1.jpg'`、`'d:\1.jpg'`
- Or start the Python interpreter with administrator privileges.

But you've already tried these solutions? That's tricky.

Let's simplify the problem. You can use `open()` to determine whether you have modification privileges:
```py
>>> f = open(path, 'r')    # open it with readonly mode
>>> f = open(path, 'wb')   # open it with write+binary mode
PermissionError: [Errno 13] Permission denied: 'c:\\Users\\1.jpg'
```
If you can write a file with `open()`, then pyexiv2 can write that file too.
If you can not write a file with `open()`, you can try other solutions. like https://www.geeksforgeeks.org/how-to-fix-permissionerror-errno-13-permission-denied-in-python/

**Comment by JoeWise** [comment]
I realized after looking closer that even though I had full permissions enabled, the file in question was marked as "Read Only", which prevented any writes from occurring. Running ```os.chmod(file_path, 0o666)```, as specified on the page you link to, fixes this issue.

Thanks for your help even though it turns out this was not a pyexiv2 issue!

**Comment by LeoHsiao1** [comment]
Fine
