### ISSUE TITLE
Image.modify_xmp crashes if pyexiv2 was imported after PySide6

### ISSUE THREAD

**Issue by wedesoft** [LeoHsiao1/pyexiv2#148]
More a comment than an issue :)
Just wanted to share this in case anybody else encounters this.
I had Image.modify_xmp crashing in a GUI application and in the end the workaround was to import pyexiv2 before any of the PySide6 submodules.

**Comment by LeoHsiao1** [comment]
Thanks for sharing, it does help!
This is probably because pyexiv2 depends on some C++ library that conflicts with PySide6. But I don't have the ability to troubleshoot their dependencies in depth.
