### ISSUE TITLE
Hint for using read_exif, read_xmp, read_iptc, read_comment

### ISSUE THREAD

**Issue by RalfPeter** [LeoHsiao1/pyexiv2#151]
Good morning,
"For all those who have encountered difficulties using the functions read_exif, read_xmp, and read_iptc. From time to time, my script crashed with a runtime error without any further error message. I suspected the cause was in the coding of exiv2 and experimented with different images. I discovered that some images contained metadata that was not UTF-8 encoded, but rather ISO-8859-1. So I wrote the following routines (analogously, of course, for XMP, IPTC, and comments as well). Perhaps someone will find it helpfull:

```
    # -------------------------------------------------------------------------------------------
    def _log_unicode_decode_details(self, e: UnicodeDecodeError, verbose=False):
        error_details = [e.encoding, e.object, e.start, e.end, e.reason]
        # Übergabe an die log-Funktion
        if verbose:
            log('EXIF unicode_decode', f"Fehler im Foto {self.file.name}: Typ: {type(e).__name__}", *error_details, level=ERROR)

    # -------------------------------------------------------------------------------------------
    def _read_exif(self):
        # encoding standard is utf-8, but could be iso-8859-1
        try:
            data = self.image.read_exif(encoding=ENCODING_UTF)
        except UnicodeDecodeError as e:
            # Übergabe an die log-Funktion
            self._log_unicode_decode_details(e)
            try:
                data = self.image.read_exif(encoding=ENCODING_ISO)
            except UnicodeDecodeError as e:
                # Übergabe an die log-Funktion
                self._log_unicode_decode_details(e, verbose=True)
                raise UnicodeDecodeError

        return data
```

**Comment by LeoHsiao1** [comment]
I am closing this issue now. Hopefully others with the same problem will search for this issue.

**Comment by RalfPeter** [comment]
Thank you Leo,
my only idea was that anybody with the same problem will have an advice how to use encoding with your pyexiv2. Thank you for your additional comment.
