### ISSUE TITLE
Library won't install on macOS 15.0.1

### ISSUE THREAD

**Issue by richardthegit** [LeoHsiao1/pyexiv2#152]
Apple seem intent on making developers lives harder with every release, and I'm damned if I can see what's going wrong here:

```
pip install pyexiv2
ERROR: Ignored the following yanked versions: 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.4.1, 2.5.0, 2.6.0
ERROR: Could not find a version that satisfies the requirement pyexiv2 (from versions: none)
ERROR: No matching distribution found for pyexiv2
```

Running pip with -vvv I get loads of messages like this, like it's look for an architecture and not finding a match:

```
Skipping link: none of the wheel's tags (cp39-none-manylinux2014_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/5e/42/62b223eddb6dfa92f0854b6a6032c9199d6722f6cdc0c5d346cdbc541a66/pyexiv2-2.15.0-cp39-none-manylinux2014_x86_64.whl (from https://pypi.org/simple/pyexiv2/) (requires-python:>=3.6)
```

Any ideas? 

Many thanks in advance.

**Comment by LeoHsiao1** [comment]
Surprised, I didn't know MacOS 15 was released.
Currently pyexiv2 is built on MacOS 14, I guess it's compatible with MacOS 15.
Please help me try it out:
1. Visit https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.15.0
2. Download a `<your_python_version>-macosx_14_0_arm64.whl` package, rename it to `xx-macosx_15_0_arm64.whl`, and run `pip instal xx.whl`. 
3. If you can't install it successfully, I have to build the new pyexiv2 on macOS 15.

**Comment by richardthegit** [comment]
Hi - thanks for replying so quickly 👍

I followed your instructions and it worked! Does that mean you can reuse that package to update pip?

**Comment by richardthegit** [comment]
Fantastic - thanks! Appreciate your work on this tool - it's very useful.

Could you let me know when it's available please and I'll close this issue...

**Comment by LeoHsiao1** [comment]
It's still a few days away.
MacOS 15 is so new that pypi.org doesn't recognize it yet.
https://github.com/pypi/warehouse/pull/16877

If this is indeed a pypi.org issue, then you should be able to install `xx-macosx_14_0_arm64.whl` directly, without renaming it to `xx-macosx_15_0_arm64.whl`.

**Comment by richardthegit** [comment]
Understood! 🫡
Trust me if I could avoid using macOS I would - it's never easy! 🤦‍♂️

**Comment by LeoHsiao1** [comment]
Now pypi is updated, and pyexiv2 doesn't need to be updated.
You should be able to execute `pip install pyexiv2` on a MacOS 15 computer. pip will download `xx-macosx_14_0_arm64.whl` and install it.

**Comment by richardthegit** [comment]
Indeed that works! Thanks again for your efforts. 👏
