### ISSUE TITLE
Missing pyexiv2 Builds for Python 3.13 (cp313)

### ISSUE THREAD

**Issue by stefanbj** [LeoHsiao1/pyexiv2#153]
CPython 3.13 was released 2024-10-07, and a new build is needed enable upgrades to the new release;
specifically it seems the following combination needs to be **added**:
- Build on Linux (ubuntu-22.04, **3.13**, 0.28.3)
- Build on MacOS (macos-15, **3.13**, 0.28.3)
- Build on Windows (windows-2019, **3.13**, 0.28.3

I this is supposedly all that is needed to fix the issue is a simple change to: [.github/workflows/build.yml](https://github.com/LeoHsiao1/pyexiv2/blob/master/.github/workflows/build.yml)

```
- python_version: [3.7, 3.8, 3.9, '3.10', '3.11', '3.12']
+ python_version: [3.7, 3.8, 3.9, '3.10', '3.11', '3.12', '3.13']

```

**Comment by LeoHsiao1** [comment]
Thank you for the information.
I just released pyexiv2 [v2.15.3](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.15.3) .
