### ISSUE TITLE
Wrong encoding causes an exception

### ISSUE THREAD

**Issue by regexgit** [LeoHsiao1/pyexiv2#155]
Some fields have incorrect encoding and I get the error message (on  "read_exif()" for exemple):

"builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: unexpected end of data"

I'd like to have a warning rather than an exception (I don't care about the problematic fields) , as this interrupts my scripts.

Attached is an exiv2 dump of an image with this problem (.txt because  .exv refused by github).

[canon_psu.txt](https://github.com/user-attachments/files/18129887/canon_psu.txt)

**Comment by LeoHsiao1** [comment]
Hi!
If the image data can't be decoded by utf-8, then you need to guess its correct encoding format.
```py
img.read_exif(encoding='??')
```

Since you don't relate problematic fields, you can execute:
```py
img.read_exif(encoding='ISO-8859-1')
```
ISO-8859-1 is a special encoding that defines all encoded values for a single byte.
Any data, regardless of its encoding format, can be decoded by ISO-8859-1. It just doesn't get the original data. Like this:
```py
>>> bytes = '你'.encode('gbk')
>>> bytes.decode('gbk')   # correct format
'你'
>>> bytes.decode('ISO-8859-1')  # wrong format, but no exception is thrown
'Äã'
>>> bytes.decode('utf-8')  # wrong format, and threw an exception
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
```

**Comment by LeoHsiao1** [comment]
ISO-8859-1 is a superset of ASCII, which includes characters from the Latin alphabet, Greek, and Arabic.
So you can still read these letters. Letters from other languages cannot be decoded by ISO-8859-1.
```py
>>> 'hello'.encode('ISO-8859-1')
b'hello'
>>> _.decode('ISO-8859-1')
'hello'
```

**Comment by regexgit** [comment]
For the problematig tag encoding is “unknown” but yes the advantage of forcing it to 'ISO-8859-1' is to eliminate the exception. But my others tags are UTF-8 encoded so I solved the problem with this code:

```
try:
    exif = img.read_exif()
except UnicodeDecodeError:
    exif = img.read_exif(encoding='ISO-8859-1')
```
It bugs me to add 8 lines of code (with read_xmp also) each time I read a tag: I went to your code where the exception was generated and in file convert.py , line 45, I replaced ”tag   = tag.decode(encoding)" by:
```
try:
    value = value.decode(encoding)
except UnicodeDecodeError:
    value = value.decode(encoding='ISO-8859-1')
```
I hope I haven't broken everything, but for the moment it's fine with me !

**Comment by LeoHsiao1** [comment]
Your solution is fine.
I hope other users who see this issue will find it useful.
In short, there are two options when encountering a UnicodeDecodeError:
- Find the correct decoding format.
  ```py
  img.read_exif(encoding='??')
  ```
- Force decoding with ISO-8859-1.
  ```py
  img.read_exif(encoding='ISO-8859-1')
  ```
