### ISSUE TITLE
Cannot open DNG files

### ISSUE THREAD

**Issue by djotaku** [LeoHsiao1/pyexiv2#16]
traceback: 

Traceback (most recent call last):
  File "/home/ermesa/Programming Projects/python/photo_stats/photostats/lenses.py", line 66, in <module>
    test_exif = get_exif.get_exif(test_photos)
  File "/home/ermesa/Programming Projects/python/photo_stats/photostats/get_exif.py", line 44, in get_exif
    this_image = Image(image)
  File "/home/ermesa/Programming Projects/python/photo_stats/venv/lib64/python3.7/site-packages/pyexiv2/core.py", line 16, in __init__
    self.img = api.open_image(filename.encode(encoding))
RuntimeError: Directory Canon with 25665 entries considered invalid; not read.

file: https://www.dropbox.com/s/c1i96a743mx0svj/Canon%20EOS%20Rebel%20XT.dng?dl=0

**Comment by LeoHsiao1** [comment]
This is an error that exiv2 encountered while reading the image. This could happen in two ways:
1. This error is fatal and prevents you from reading the image.
2. This error is a warning that you can choose to ignore.

In the first case, there was nothing I could do.
In the second case, you can increase the log level to ignore the warning:
```python
>>> import pyexiv2
>>> pyexiv2.set_log_level(4)
>>> img = pyexiv2.Image(r'.\pyexiv2\tests\1.jpg')
>>> img.close()
```

Reference: [log](https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md#log)

**Comment by LeoHsiao1** [comment]
Does that solve your problem?

**Comment by djotaku** [comment]
Excellent! It totally does! Thank you!
