### ISSUE TITLE
modify_xmp() does not properly change tags

### ISSUE THREAD

**Issue by Fujianshida** [LeoHsiao1/pyexiv2#20]
I use ```modify_xmp()``` to replace the tags on an image. 
Then I use ```read_xmp()``` to check the results. As expected, the image has the new set of tags. 
Now I check the properties of the file by right clicking on the file in windows explorer. 
However, the old tags are still there. 
The tags as reported by ```read_xmp()``` are now incorrect.

**Comment by LeoHsiao1** [comment]
An image label in Windows explorer might correspond to more than one label in exiv2.
You may not have found the right label.

**Comment by Fujianshida** [comment]
Solved: iptc also contains tags. and these were being shown on windows explorer in addition to the xmp tags. solution is to use ```modify_xmp()``` and ```modify_iptc()``` to modify both sets of tags. might be worth adding to the tutorial that some software( windows explorer and other photo managing software) use both types of tags, so you may need to edit both sets?

apologies for raising as a bug, this is not a bug. 
I think it would be useful to add more detail to the tutorial.
