### ISSUE TITLE
error while installing pyexiv2

### ISSUE THREAD

**Issue by arhackbom** [LeoHsiao1/pyexiv2#27]
Collecting pyexiv2
  Using cached pyexiv2-2.3.1.tar.gz (4.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Osypvi/pyexiv2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Osypvi/pyexiv2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-XnkqaZ                                               
         cwd: /tmp/pip-install-Osypvi/pyexiv2/                             
    Complete output (5 lines):                                             
    Traceback (most recent call last):                                     
      File "<string>", line 1, in <module>                                 
      File "/tmp/pip-install-Osypvi/pyexiv2/setup.py", line 4, in <module> 
        with open('README.md', encoding='utf-8') as f:                     
    TypeError: 'encoding' is an invalid keyword argument for this function 
    ----------------------------------------                               
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LeoHsiao1** [comment]
Are you using python2?
pyexiv2 only supports python3.5 or above.

**Comment by arhackbom** [comment]
ok noted. thx.
