### ISSUE TITLE
Outdated function

### ISSUE THREAD

**Issue by Kikey-y** [LeoHsiao1/pyexiv2#30]
Hello I'm trying to change the MD5 hash of a file using the code from this question https://stackoverflow.com/questions/15254514/how-can-i-change-an-images-md5-hash-in-python
But since the reply is pretty old it's saying ```AttributeError: module 'pyexiv2' has no attribute 'ImageMetadata```
What's the new function??

**Comment by LeoHsiao1** [comment]
Hi!
You're talking about the old pyexiv2, which has stopped updating. This is its website: <https://launchpad.net/pyexiv2/>
If you use my pyexiv2, please look at this document: <https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md>
