### ISSUE TITLE
How can I use opencv image into pyexiv2?

### ISSUE THREAD

**Issue by ibrahimLearning** [LeoHsiao1/pyexiv2#32]
Thanks for nice repo.
img=cv.imread('1.JPG')

now how can I use img data in pyexiv2?

**Comment by LeoHsiao1** [comment]
You need to save the image to a file, or get its binary content.
- Class `pyexiv2.Image(filename, encoding='utf-8')` is used to open an image based on the file path.
- Class `pyexiv2.ImageData(data: bytes)` is used to open an image from bytes data.
