### ISSUE TITLE
Compile binaries for python 3.9

### ISSUE THREAD

**Issue by JWCook** [LeoHsiao1/pyexiv2#34]
It would be convenient to have pre-compiled binaries for python 3.9, which was [released](https://www.python.org/downloads/release/python-390/) a couple months ago. Thank you!

**Comment by LeoHsiao1** [comment]
Ok, I will add it in the next few days.

**Comment by JWCook** [comment]
That would be great, thank you very much! And thanks for your work on this library, it's been very useful for me.

**Comment by LeoHsiao1** [comment]
Thank you for using it.
I just released the [v2.3.2](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.3.2)
It took me two nights to install MacOS on VMware virtual machine.

**Comment by JWCook** [comment]
Thank you for doing that, I appreciate it! I just tested v2.3.2 with python 3.9 and it works.

MacOS setup in a VM sounds difficult. It may be possible to automate that using GitHub Actions, since they [host runners for macOS Catalina 10.15](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-software).

If I need this to be compiled again for a future version (like python 3.10, estimated release in October 2021), I would be willing to help set that up.
