### ISSUE TITLE
How can I set a list as dc.subject?

### ISSUE THREAD

**Issue by marcelklehr** [LeoHsiao1/pyexiv2#5]
I tried setting a list, but it wouldn't accept that saying it requires a string. A comma separated string will just render a string, though, which doesn't get picked up by other software as a list.

Appreciate your help :)

**Comment by LeoHsiao1** [comment]
Thanks for your report. That's because I forgot to convert it to an array. I will correct it in the next few days.

**Comment by marcelklehr** [comment]
Awesome :tada:

**Comment by LeoHsiao1** [comment]
Hi!
This problem has been fixed in version [v1.2.4](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v1.2.4).

**Comment by marcelklehr** [comment]
Thanks so much! :)

**Comment by marcelklehr** [comment]
This fabulous library allowed me to create [marcelklehr/wutsdis](https://github.com/marcelklehr/wutsdis) :)

**Comment by LeoHsiao1** [comment]
It's my pleasure.
