### ISSUE TITLE
working together with pillow?

### ISSUE THREAD

**Issue by mokko** [LeoHsiao1/pyexiv2#57]
Hi Leo,

thanks for a wonderful module and maintaining it! 

Is there a way that I can open an image from pillow directly without writing it to the disk first?

Thanks!

**Comment by LeoHsiao1** [comment]
As far as I know, you can load the image into memory, then read and write the image from memory:
```py
# Load the image into memory
import io
buf = io.BytesIO()
with open('1.jpg', 'rb') as f:
    buf.write(f.read())

# Open the image in pillow
from PIL import Image
with Image.open(buf) as img:
    img.save(buf, format="JPEG", quality=95)

# Open the image in pyexiv2
import pyexiv2
buf.seek(0)
with pyexiv2.ImageData(buf.read()) as pyexiv2_img:
    pyexiv2_img.read_exif()

```

In addition, I found that Pillow lost metadata when it saved the image, for example by executing the following code:
```py
with Image.open('1.jpg') as img:
    img.save('2.jpg', format="JPEG", quality=95)
```
To avoid losing metadata, you should back up the metadata before Pillow opens the image, and write the metadata after Pillow saves the image.

**Comment by LeoHsiao1** [comment]
`io.BytesIO` doesn't support modification, so Pillow should save the image like this:
```py
saved_buf = io.BytesIO()
with Image.open(buf) as img:
    img.save(saved_buf, format="JPEG", quality=95)

```

**Comment by LeoHsiao1** [comment]
I was wrong, `io.BytesIO` supports modification, just truncate it:
```py
buf.truncate(0)
buf.seek(0)
```

**Comment by mokko** [comment]
Thank you!
