### ISSUE TITLE
Directory Canon with 7424 entries considered invalid; not read.

### ISSUE THREAD

**Issue by mlove4u** [LeoHsiao1/pyexiv2#58]
My code:
```py
# Mac bigsur, Python3.7.6
from pyexiv2 import Image

img = Image(r'IMG_9699.jpg')
img.read_exif()
```
Error:
```py
Traceback (most recent call last):

  File "/Users/＊＊＊/Desktop/exiv2_test/pyexiv2-master/sample.py", line 3, in <module>
    img = Image(r'IMG_9699.jpg')
  File "/Users/＊＊＊/Desktop/exiv2_test/pyexiv2-master/pyexiv2/core.py", line 16, in __init__
    self.img = exiv2api.Image(filename.encode(encoding))
RuntimeError: Directory Canon with 7424 entries considered invalid; not read.
```
With exiv2 command line tool, it returns  error and metadata.
![e](https://user-images.githubusercontent.com/18019314/110430664-0d628980-80f0-11eb-88b2-2170020b5828.png)

I am sorry I cannot attach the jpg file due to the copyright issue. 
Is it possible to ignore the error and get the metadata?
Thank you.

**Comment by LeoHsiao1** [comment]
Yes!
Please try to change the [log level](https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md#log):
```py
pyexiv2.set_log_level(4)
```

**Comment by mlove4u** [comment]
@LeoHsiao1 Thanks. It works!
