### ISSUE TITLE
something wrong! Could not find module 'C:\Python39\lib\site-packages\pyexiv2\lib\exiv2.dll'

### ISSUE THREAD

**Issue by logofun** [LeoHsiao1/pyexiv2#60]
![image](https://user-images.githubusercontent.com/22115036/112006509-bda7a780-8b5e-11eb-8510-7b122dc0e40d.png)

when I install the module, and then import pyexiv2 , it show wrong(as the above picture)

**Comment by LeoHsiao1** [comment]
Could not find exiv2.dll. It could be one of two cases :
- exiv2.dll does not exist.
- exiv2.dll exists, but it is not compatible with the computer.

Let's check the first case first. Please show what's in your directory:
```sh
C:\Python39\Lib\site-packages\pyexiv2\lib
```

**Comment by logofun** [comment]
![image](https://user-images.githubusercontent.com/22115036/112145048-d83c5800-8c14-11eb-95eb-993c5cf83db1.png)
the file(exiv2.dll) exist in the right way.
How to check the problem via the 2rd case.
thanks for your respond

**Comment by LeoHsiao1** [comment]
Next, Try importing exiv2.dll in the Python interpreter:
```py
>>> import ctypes
>>> ctypes.CDLL(r'C:\Python39\Lib\site-packages\pyexiv2\lib\exiv2.dll')
```
If it fails, it indicates an incompatibility.

**Comment by logofun** [comment]
![image](https://user-images.githubusercontent.com/22115036/112156624-60c0f580-8c21-11eb-9513-861e4f6ba61e.png)
oh no, the same wrong
how can I do.
My computer is surface pro with the windows10 system.

**Comment by LeoHsiao1** [comment]
What kind of Python interpreter do you use? Only CPython supports importing C++ libraries.
```py
>>> import platform
>>> platform.python_implementation()
'CPython'
```

**Comment by LeoHsiao1** [comment]
If you're using CPython and still can't import exiv2.dll, you'll have to compile it yourself.
This is a tricky process:
1. Install Visual Studio to compile exiv2 manually. See the [docs ](https://github.com/Exiv2/exiv2) of Exiv2.
2. Copy exiv2.dll to compile pyexiv2. See the [docs](https://github.com/LeoHsiao1/pyexiv2/tree/master/pyexiv2/lib) of pyexiv2.

**Comment by logofun** [comment]
It seems that the computer environment is the real reason.
because when I use another PC and handle the program as the same way, it shows OK.
by the way , I am using CPython in the both computer.
Copy exiv2.dll from the github/LeoHsiao1/pyexiv2, it is not working.
From the others methods, such as 'os.add_all_directory('....')',it's also wrong
How to compile exiv2 manually?

**Comment by LeoHsiao1** [comment]
I still think that exiv2.dll should be compatible with your computer, because your computer is not special.
Maybe you can try installing Python3.5 and then execute `pip install pyexiv2`.
Finally, you can find the Exiv2 repository on GitHub, which is well documented.

**Comment by LeoHsiao1** [comment]
I just tried using pyexiv2 on a newly installed Windows 10, it works:
```py
C:\Users\Leo>python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyexiv2
```

**Comment by logofun** [comment]
the same version Python, One in the lenovo notebook computer, it's ok, just like your result.
the other in Surface pro, it's also wrong

**Comment by LeoHsiao1** [comment]
I found the answer. This is because the Windows computer lacks C++ environment. Please try to install [Microsoft Visual C++ Redistributable for Visual Studio 2019](https://visualstudio.microsoft.com/zh-hans/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2019).
