### ISSUE TITLE
Unable to read exift data! 

### ISSUE THREAD

**Issue by claudiaximenaro** [LeoHsiao1/pyexiv2#61]
Hi, I have a problem with reading the exif and iptc data from *.png files.
When I use Exiftool, I can see that the information is there, however when I use pyexiv2 my exif/iptc data dictionaries are empty, it only happens with png files, for the rest (jpg,tiff,) it works.

**Comment by LeoHsiao1** [comment]
pyexiv2 supports reading and writing Exif, IPTC amd XMP metadata from PNG images.
For example:
```py
leo@Leo:/mnt/d$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyexiv2
>>> img = pyexiv2.Image('1.png')
>>> img.modify_exif({'Exif.Image.Artist': 'TEST'})
>>> img.read_exif()
{'Exif.Image.Artist': 'TEST'}
>>> img.modify_iptc({'Iptc.Application2.ObjectName': 'TEST'})
>>> img.read_iptc()
{'Iptc.Application2.ObjectName': 'TEST'}
```

You can try to read images with [exiv2](https://www.exiv2.org/).
- If exiftool can read metadata, but exiv2 can't, then it's exiv2's problem.
- If exiv2 can read metadata, but pyexiv2 can't, then it's pyexiv2's problem.

**Comment by claudiaximenaro** [comment]
Thank you. Indeed pyexif2 supports png files, the problem seems to come from the photos that are very dated (2010) and at that time PNG didn't have a formal EXIF chunk, so what I am seeing with exiftool is actually the information coming from the xmp data that was added later.
