### ISSUE TITLE
Support CR3 files via Exix 0.27.4RC

### ISSUE THREAD

**Issue by piratenpanda** [LeoHsiao1/pyexiv2#62]
I don't know if this is the right place to ask but currently I don't see a possibility to make use of the new features introduced by 0.27.4 (RC,2,3) which I am running on my system. Will this be possible as soon as the GM release happens or if this is not the place to ask, where should I go or if one can help, what needs to be done to support this feature?

**Comment by LeoHsiao1** [comment]
Currently, pyexiv2 uses the 0.27.2 version of Exiv2.
The new version adds few features, but may not be compatible with older Linux systems. So I haven't updated it.
As you requested, I will update pyexiv2 after Exiv2 0.27.4GM release.
If you're in a hurry, you can compile it yourself: [pyexiv2/lib](https://github.com/LeoHsiao1/pyexiv2/blob/master/pyexiv2/lib/README.md)

**Comment by piratenpanda** [comment]
Thanks for the fast reply. I will try, thanks for the hint

**Comment by LeoHsiao1** [comment]
Hi, I added this feature in [v2.6.2](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.6.2).

**Comment by piratenpanda** [comment]
thanks
