### ISSUE TITLE
problem in puthon 2 with open and encoding keyword

### ISSUE THREAD

**Issue by martinbjerge** [LeoHsiao1/pyexiv2#7]
In setup.py open is called with keywork "encoding" (line 4) 
this don't work in python 2, hence sugest to "import io" and use "io.open" insted.

eg. see this:
https://stackoverflow.com/questions/25049962/is-encoding-is-an-invalid-keyword-error-inevitable-in-python-2-x

Error from pip instal:
(base) C:\Users\MartinHuusBjerge>pip install pyexiv2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyexiv2
  Using cached https://files.pythonhosted.org/packages/c4/f0/acd45defbb3dd1147f47837ce06f27b3d7978a3fc47d24556cf630bbccd0/pyexiv2-1.3.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\martin~1\\appdata\\local\\temp\\pip-install-wgew3s\\pyexiv2\\setup.py'"'"'; __file__='"'"'c:\\users\\martin~1\\appdata\\local\\temp\\pip-install-wgew3s\\pyexiv2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\martin~1\appdata\local\temp\pip-install-wgew3s\pyexiv2\pip-egg-info'
         cwd: c:\users\martin~1\appdata\local\temp\pip-install-wgew3s\pyexiv2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\martin~1\appdata\local\temp\pip-install-wgew3s\pyexiv2\setup.py", line 4, in <module>
        with open("README.md", encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LeoHsiao1** [comment]
Hi!
I developed this pyexiv2 based on python3(64bit), so it won't work on python2.
You have two options:
- Use my pyexiv2 on python3(64bit).
- Use the [pyexiv2](https://launchpad.net/pyexiv2) developed by another team, which is based on Python2, but is no longer maintained.

**Comment by LeoHsiao1** [comment]
Wooo…I'm going to close this issue.

**Comment by martinbjerge** [comment]
> Hi!
> I developed this pyexiv2 based on python3(64bit), so it won't work on python2.
> You have two choices:
> 
> * Use my pyexiv2 on python3(64bit).
> * Use the [pyexiv2](https://launchpad.net/pyexiv2) developed by another team, which is based on Python2, but no longer maintained.

Thanks for getting back to me so fast. 
OK, i was just under the impression that pyexiv2 was for python2 and py3exiv2 was for python3.
Also i don't get why your project is the one beeing installed when i use pip install (in python2) and not the other one thats for python2.
But all good i will get it up and running.

**Comment by LeoHsiao1** [comment]
The pyexiv2 and py3exiv2 projects you mentioned are developed several years ago, while I redeveloped this pyexiv2 in 2019. Their names are very similar, haha.
