### ISSUE TITLE
Unable to read HEIC file

### ISSUE THREAD

**Issue by davidwu111** [LeoHsiao1/pyexiv2#70]
Hi, I'm trying to read EXIF for different types of photos and jpg have no problem at all. But when comes to HEIC it says unknown image type. I did went to exiv2 release notes and v0.27.4 says supported HEIC. Any suggestion? Thanks! 

`self.img = exiv2api.Image(filename.encode(encoding))
RuntimeError: C:\test11\IMG_0005_20180212133649.heic: The file contains data of an unknown image type`

Python: 3.9
pyexiv2: 2.6.0
OS: Win 10

**Comment by LeoHsiao1** [comment]
I don't know the HEIC format.
I just tried to read it with exiv2 0.27.4 and it also failed:
```sh
D:\>C:\Users\Leo\Downloads\exiv2-0.27.4-2019msvc64\bin\exiv2.exe C:\Users\Leo\Desktop\sample1.heic
Exiv2 exception in print action for file C:\Users\Leo\Desktop\sample1.heic:
C:\Users\Leo\Desktop\sample1.heic: The file contains data of an unknown image type
```
I'll look into that over the weekend.

**Comment by LeoHsiao1** [comment]
Oh, this feature of Exiv2 is disabled by default: <https://github.com/Exiv2/exiv2#219-support-for-bmff-files-cr3-heif-heic-and-avif>

**Comment by davidwu111** [comment]
Thanks Leo, looks like not much can do here since patent related issue.

**Comment by LeoHsiao1** [comment]
Hi, I added this feature in [v2.6.2](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.6.2).
