### ISSUE TITLE
GLIBC Version 2.29

### ISSUE THREAD

**Issue by mokrueger** [LeoHsiao1/pyexiv2#73]
The new version 2.6 has been giving me this error with my dockerfile (based on python3.8.5-slim) which natively runs version glibc version 2.28.

oserror: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.8/site-packages/pyexiv2/lib/libexiv2.so)

Going back to version 2.5.0 fixed the issue for me.

Just letting you know that issue exists ;)

**Comment by LeoHsiao1** [comment]
Thank you. This is because I updated the CI environment of pyexiv2.
pyexiv2 is now compiled with GLIBC 2.29. So, you need to upgrade your GLIBC library, or upgrade your Linux distribution.
See the [Tutorial](https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md#faq) for details.
