### ISSUE TITLE
pyexiv2.enableBMFF()启用失败

### ISSUE THREAD

**Issue by erdiansanheng** [LeoHsiao1/pyexiv2#74]
调用pyexiv2.enableBMFF()返回False，请问是什么情况

**Comment by LeoHsiao1** [comment]
好像是 Windows 版的构建包禁用了这个功能，等我调试下

**Comment by LeoHsiao1** [comment]
我重新编译了 Windows 系统的库文件，发布了 [v2.6.3](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.6.3).

**Comment by erdiansanheng** [comment]
可用了，感谢
