### ISSUE TITLE
png读取不到任何元数据，比如拍摄日期

### ISSUE THREAD

**Issue by helinxuan** [LeoHsiao1/pyexiv2#77]

**Comment by LeoHsiao1** [comment]
1. 你的 PNG 图片本来有元数据吗？
2. 给这个 PNG 写入元数据，可以再读取到吗？

**Comment by helinxuan** [comment]
你好png图片我设置了拍照日期，尝试了所有的read方法，打印出来都是空的，我用同样的方法修改jpg就可以读取并修改成功
![image](https://user-images.githubusercontent.com/36950713/125776466-9384676f-e8d0-4151-b9c0-a94ed1948ec6.png)

**Comment by LeoHsiao1** [comment]
可以把你这张图片压缩之后发我邮箱试试吗？
或者你尝试写入元数据，再读取

**Comment by helinxuan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeoHsiao1/pyexiv2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeoHsiao1/pyexiv2] png读取不到任何元数据，比如拍摄日期 (#77)





 
可以把你这张图片压缩之后发我邮箱试试吗？
 或者你尝试写入元数据，再读取

**Comment by helinxuan** [comment]
好的已经发你邮箱了，我尝试了写入后读取，可以读出来，但是在电脑上看拍摄日期并没有被改动

**Comment by LeoHsiao1** [comment]
我没有收到，请做成压缩包之后发到这个邮箱：
leohsiao@foxmail.com

**Comment by LeoHsiao1** [comment]
我尝试读取这张 PNG 图片，它存在 XMP 元数据：
```py
>>> img = pyexiv2.Image(r"C:\Users\Leo\Desktop\2014-09-28 153216.png")
>>> img.read_exif()
{}
>>> img.read_iptc()
{}
>>> img.read_xmp()
{'Xmp.xmp.CreateDate': '9119-06-23T19:45:17.834'}
```

然后我用 [exiftool](https://exiftool.org/) 查看其数据结构，如下：
```sh
leo@Leo:/$ exiftool -v "2014-09-28 153216.png"
  ExifToolVersion = 12.29
  FileName = 2014-09-28 153216.png
  Directory = .
...
PNG pHYs (9 bytes):
  + [BinaryData directory, 9 bytes]
  | PixelsPerUnitX = 3779
  | PixelsPerUnitY = 3779
  | PixelUnits = 1
PNG tEXt (33 bytes):
  CreationTime = 1997:07:15 18:46:52
PNG IDAT (9 chunks, total 549509 bytes)
PNG IEND (end of image)
```
可见它没有符合 EXIF、IPTC、XMP 规范的元数据，只有一个 PNG tEXt 字段记录了拍摄日期。

**Comment by helinxuan** [comment]
感谢解答，我尝试把图片转化成jpg格式就可以了
