### ISSUE TITLE
Please provide a way to easily access the version of pyexiv2 itself at runtime

### ISSUE THREAD

**Issue by damonlynch** [LeoHsiao1/pyexiv2#80]
Thanks for taking the time to write this wrapper around exiv2! I especially appreciate it's so simple to install.

Regarding the issue, this would be great, for example:

```bash
import pyexiv2
pyexiv2.__version__
```

Not a big deal I know, but useful all the same. 😄

**Comment by LeoHsiao1** [comment]
Hi there! Thank you for your advice.
I have added the API and released [v2.6.4](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.6.4) .
