### ISSUE TITLE
FileNotFoundError: Could not find module "exiv2.dll"

### ISSUE THREAD

**Issue by Baa14453** [LeoHsiao1/pyexiv2#87]
This library works great in Ubuntu but I just tried it in Windows and got the following error:

```
FileNotFoundError: Could not find module 'C:\Users\Test\AppData\Local\Programs\Python\Python310\lib\site-packages\pyexiv2\lib\exiv2.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

exiv2.dll exists fine, any ideas what might be causing the error?
![image](https://user-images.githubusercontent.com/9057997/140606864-ff93b6b9-24de-4320-8048-4eaea647cbe9.png)

This is a fresh installation of Windows 11, pyexiv2 installed through pip

**Comment by LeoHsiao1** [comment]
Hi
Have you tried the measures in the [docs](https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md#installation)?

**Comment by Baa14453** [comment]
@LeoHsiao1 Sorry totally missed that, didn't occur to me that the Tutorial would have installation docs somehow
Thanks that worked, I needed to install VC Redistributable :+1:

**Comment by LeoHsiao1** [comment]
I also didn't expect Windows to lack a C++ runtime. The solution was discovered by accident.

**Comment by zR00t1** [comment]
环境：Windows11  python3.7.4

我用这段测试代码，直接运行py文件是正常的
![image](https://user-images.githubusercontent.com/46400438/141609445-61c513ae-5a98-4580-b69e-99d61719430a.png)

当我用pyinstaller -F test.py将这个py文件打包成exe并运行该exe的时候，同样提示该问题：

`__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\zR00t1\\AppData\\Local\\Temp\\_MEI175202\\pyexiv2\\lib\\exiv2.dll'. Most probably this dynlib/dll was not found when the application was frozen.`

然后，我确认了电脑中已安装VC++ Redistributable，并且将exiv2.dll文件放到test.exe同目录下再运行，仍然出现该错误

![image](https://user-images.githubusercontent.com/46400438/141609724-07514e4c-4ba2-40d3-9f95-c8344850aea5.png)

最后，使用pyinstaller -D test。打包成一个目录，并将exiv2.dll文件也放到该目录下，上面的问题没有了，但是出现了新问题：No module named ‘exiv2api’

![image](https://user-images.githubusercontent.com/46400438/141609895-61300c94-d36c-481d-a326-e30a268eb382.png)

实在是解决不了了

**Comment by LeoHsiao1** [comment]
这是因为 pyinstaller 没有将 `pyexiv2/lib` 目录下的 exiv2.dll 和 exiv2api.pyd 库一起打包，没那么智能。搜了下，这是 pyinstaller 的常见问题：<https://stackoverflow.com/questions/57935948/pyinstaller-gives-importerror-dll-load-failed>
看起来配置挺麻烦

**Comment by barakplasma** [comment]
what worked for me to include pyexiv2 into a PyInstaller bundle for Linux was adding this hook file https://github.com/pyinstaller/pyinstaller/discussions/6404#discussioncomment-5390655

**Comment by acer1456** [comment]
if anyone using windows to use pyinstaller, i found the solution for it, which is the command below.

you need to use --add-binary for your "exiv2.dll" and use --add-data for your "exiv2api.pyd".

pyinstaller --add-binary “C:\Python310\Lib\site-packages\pyexiv2\lib\exiv2.dll;.” --add-data “C:\Python310\Lib\site-packages\pyexiv2\lib\py3.10-win\exiv2api.pyd;.” --onefile  ccc.py

it should be success on windows.

> 环境：Windows11 python3.7.4
> 
> 我用这段测试代码，直接运行py文件是正常的 ![image](https://user-images.githubusercontent.com/46400438/141609445-61c513ae-5a98-4580-b69e-99d61719430a.png)
> 
> 当我用pyinstaller -F test.py将这个py文件打包成exe并运行该exe的时候，同样提示该问题：
> 
> `__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\zR00t1\\AppData\\Local\\Temp\\_MEI175202\\pyexiv2\\lib\\exiv2.dll'. Most probably this dynlib/dll was not found when the application was frozen.`
> 
> 然后，我确认了电脑中已安装VC++ Redistributable，并且将exiv2.dll文件放到test.exe同目录下再运行，仍然出现该错误
> 
> ![image](https://user-images.githubusercontent.com/46400438/141609724-07514e4c-4ba2-40d3-9f95-c8344850aea5.png)
> 
> 最后，使用pyinstaller -D test。打包成一个目录，并将exiv2.dll文件也放到该目录下，上面的问题没有了，但是出现了新问题：No module named ‘exiv2api’
> 
> ![image](https://user-images.githubusercontent.com/46400438/141609895-61300c94-d36c-481d-a326-e30a268eb382.png)
> 
> 实在是解决不了了
