### ISSUE TITLE
cannot edit Xmp.iptc.Location as expected

### ISSUE THREAD

**Issue by lipeck** [LeoHsiao1/pyexiv2#91]
Hello, I am trying to edit as so:

```
metadata = {
    "Xmp.dc.description": "description",
    "Xmp.photoshop.Headline": "headline",
    "Xmp.iptc.Location": "sublocation",
}
img.modify_xmp(metadata)
``` 
result:

```
img.read_xmp()
{
    "Xmp.iptc.Location": "",
    "Xmp.photoshop.Headline": "headline",
    "Xmp.dc.description": {'lang="x-default"': "description"},
}
```
It seems to just be this one field. I'm also unable to clear the field or overwrite anything existing.

**Comment by LeoHsiao1** [comment]
Hi
Referring to [this](https://www.exiv2.org/tags-xmp-iptc.html), Xmp.iptc.Location is a common tag.
After trying, I can modify it:
```py
>>> img.read_xmp()
{}
>>> img.modify_xmp({"Xmp.iptc.Location": "sublocation"})
>>> img.read_xmp()
{'Xmp.iptc.Location': 'sublocation'}
>>> img.modify_xmp({"Xmp.iptc.Location": "location"})
>>> img.read_xmp()
{'Xmp.iptc.Location': 'location'}
```

Is it just this picture that cannot be modified?

**Comment by lipeck** [comment]
Hi, thanks so much for looking into it for me, and also for creating this tool! I'm having this issue with any photo I try to manipulate. I'm working with .RAW images, editing the .XMP sidecar files.

**Comment by LeoHsiao1** [comment]
Sorry I don't have any raw images.
I googled some [images](https://www.signatureedits.com/free-raw-photos/) and their `xmp.iptc.location` is editable.
According to exiv2's [document](https://dev.exiv2.org/projects/exiv2/wiki/Supported_image_formats), is your image not in standard format?

**Comment by lipeck** [comment]
According to the chart, the file types I'm using should be OK:

**Type | Exif mode | IPTC mode | XMP mode | Comment mode | MIME type**
NEF | ReadWrite | ReadWrite | ReadWrite | - | image/x-nikon-nef
XMP | - | - | ReadWrite | - | application/rdf+xml

**Comment by LeoHsiao1** [comment]
Can you edit images in normal formats such as JPEG?
RAW images are not standardized across different manufacturers. Can you edit other RAW images from Google?

**Comment by lipeck** [comment]
Hi, my apologies for the slow response. I tested this with fresh images from Google. it seems that using the same methods, I can write to the location field when it does not already exist, but I cannot overwrite existing metadata. I also cannot write anything if the field already exists but is empty. Again, it is only the `xmp.iptc.location` field which this issue appears, I have been writing and overwriting to many others with great success!

**Comment by LeoHsiao1** [comment]
I don't know why. Maybe it's because RAW images are not standardized across different manufacturers?
I'm sorry I can't solve the problem.

**Comment by LeoHsiao1** [comment]
Anyway, the XMP metadata is in XML format and should all be editable.
Can you send a uneditable picture to my email?

**Comment by lipeck** [comment]
No problem, I am baffled as well... I just sent you an email with an image.

**Comment by LeoHsiao1** [comment]
Thank you for sending me the test image.
I can edit the `xmp.iptc.location` field on windows10 and ubuntu20.04 :
```py
>>> import pyexiv2
>>> img = pyexiv2.Image('unedited/test1.NEF')
>>> img.read_xmp()
{}
>>> metadata = {'Xmp.dc.description': 'description', 'Xmp.photoshop.Headline': 'headline', 'Xmp.iptc.Location': 'location', 'Xmp.photoshop.TransmissionReference': 'job ID', 'Xmp.photoshop.SupplementalCategories': 'categories'}
>>> img.modify_xmp(metadata)
>>> img.read_xmp()
{'Xmp.dc.description': 'lang="x-default" description', 'Xmp.photoshop.Headline': 'headline', 'Xmp.iptc.Location': 'location', 'Xmp.photoshop.TransmissionReference': 'job ID', 'Xmp.photoshop.SupplementalCategories': ['categories']}
>>> img.modify_xmp({"Xmp.iptc.Location": "sublocation"})
>>> img.read_xmp()['Xmp.iptc.Location']
'sublocation'
```

But I didn't have a MacOS to test. Have you tried any other computers?
Anyway, you can use `read_raw_xmp()` and `modify_raw_xmp()` to modify XMP metadata.

**Comment by lipeck** [comment]
i am using MacOS. it is the same between other macs -- using another system is not a longterm solution to this problem for me. i don't understand why this issue is persisting but it is frustrating. i'll do some tests with `read_raw_xmp()` etc. but as i am also manipulating JPGs with the same scripts it would really be best to use `read_xmp()`

**Comment by LeoHsiao1** [comment]
Both exiv2 and pyexiv2 distributions include dynamically linked libraries compiled from C++ code.
The library may not be compatible with an operating system and cannot be loaded.
But I have never had a situation where the library was loaded and some functionality was unavailable.

Thanks for your patience, please provide some more debugging information:
- What's your pyexiv2 version? You can execute `pip show pyexiv2`
- Please execute the following python code in the python interactive interpreter and copy the terminal output to this issue.
  ```py
  import pyexiv2
  img = pyexiv2.Image('test1.NEF')
  img.modify_xmp({'Xmp.dc.description': 'Hello', 'Xmp.iptc.Location': 'location'})
  img.read_xmp()['Xmp.iptc.Location']

  # Erase XMP metadata and write
  img.clear_xmp()
  img.modify_xmp({'Xmp.dc.description': 'Hello', 'Xmp.iptc.Location': 'location'})
  img.read_xmp()
  img.close()
  ```
- If you have time to download the exiv2 [distribution](https://exiv2.org/download.html), try the following command:
  ```sh
  # modify
  bin/exiv2 -M'set Xmp.iptc.Location location' test1.NEF

  # read
  bin/exiv2 -K Xmp.iptc.Location test1.NEF
  ```
  If the metadata is modified, it means exiv2 is working and pyexiv2 has a problem.

**Comment by lipeck** [comment]
thanks for your continued help!

`pip show pyexiv2`:
```
Name: pyexiv2
Version: 2.7.0
Summary: Read/Write metadata(including EXIF, IPTC, XMP), comment and ICC Profile embedded in digital images.
Home-page: https://github.com/LeoHsiao1/pyexiv2
Author: LeoHsiao
Author-email: leohsiao@foxmail.com
License: GPLv3
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by: 
```
from python interactive interpreter:
```
>>> import pyexiv2
>>> img = pyexiv2.Image('test1.NEF')
>>> img.modify_xmp({'Xmp.dc.description': 'Hello', 'Xmp.iptc.Location': 'location'})
>>> img.read_xmp()['Xmp.iptc.Location']
'location'
>>> img.clear_xmp()
>>> img.modify_xmp({'Xmp.dc.description': 'Hello', 'Xmp.iptc.Location': 'Location'})
>>> img.read_xmp()
{'Xmp.dc.description': {'lang="x-default"': 'Hello'}, 'Xmp.iptc.Location': 'Location'}
>>> img.close()
```

however, I usually write to the .xmp directly --
```
>>> import pyexiv2
>>> img = pyexiv2.Image('test1.xmp')
>>> img.modify_xmp({'Xmp.dc.description': 'hello', 'Xmp.iptc.Location': 'location'})
>>> img.read_xmp()['Xmp.iptc.Location']
'location'
>>> img.clear_xmp()
>>> img.modify_xmp({'Xmp.dc.description': 'Hello', 'Xmp.iptc.Location': 'Location'})
>>> img.read_xmp()['Xmp.iptc.Location']
'Location'
>>> img.read_xmp()['Xmp.dc.description']
{'lang="x-default"': 'Hello'}
>>> img.close()
```

i'll try to check on the exiv2 distribution this week.
