### ISSUE TITLE
is there a recommended way to iterate over the metadata groups?

### ISSUE THREAD

**Issue by tester0077** [LeoHsiao1/pyexiv2#92]
I realize hat this pyexiv2 is an extension of libexiv2, but I cannot quite understand if or how I could get the number of entries for a given group for a specific image or, iterate over a specific group and get selected tags other than a hard-code switch statement

**Comment by LeoHsiao1** [comment]
This is the [metadata](https://exiv2.org/metadata.html) that exiv2 could read.
When pyexiv2 opens an image, it automatically reads all metadata and returns a dict. It does not support reading only one tag at a time.

**Comment by tester0077** [comment]
Thank you. I am very new at python way of doing things, so this gives me a
place to start.

**Comment by LeoHsiao1** [comment]
Welcome to the world of Python and enjoy your journey.
