### ISSUE TITLE
Failure to convert

### ISSUE THREAD

**Issue by lipeck** [LeoHsiao1/pyexiv2#96]
Getting a few error messages when working with metadata from .XMP files -- this is new behavior on scripts that haven't changed.

when reading `Xmp.dc.description`:

```
Failed to convert Xmp.dc.description to Iptc.Application2.Caption
Failed to convert Xmp.dc.description to Exif.Image.ImageDescription
```

2-3 or so images for every 100 get this error but I'm not sure why these images.

**Comment by lipeck** [comment]
I think I've noticed a pattern -- I believe this error appears when a description was previously filled but was cleared manually in an application like Bridge.

**Comment by LeoHsiao1** [comment]
I guess the metadata format of the image is unusual.
Could you try to read these special images directly with the exiv2 command? <https://exiv2.org/manpage.html>
If it still prints an error, you can ask the [Exiv2](https://github.com/Exiv2/exiv2) team for help.
And I found a similar problem: <https://stackoverflow.com/questions/29579434/unable-to-parse-iptc-date-to-xmp-datetime-in-exiv2>
