### ISSUE TITLE
Cannot import name 'ImageMetadata' from 'pyexiv2'

### ISSUE THREAD

**Issue by estribiyo** [LeoHsiao1/pyexiv2#97]
I have this output when trying to import the library as original pyexiv2...

The code I use in Python 3.9 running on Windows 10 is:

```
from pyexiv2 import ImageMetadata, xmp, XmpTag, IptcTag, ExifTag
```

**Comment by LeoHsiao1** [comment]
Hi, you might be confused with these similar projects:
- [pyexiv2](https://launchpad.net/pyexiv2): It is a Python 2 binding to exiv2, hasn't been updated since 2011.
- [py3exiv2](https://pypi.org/project/py3exiv2/): It is a Python 3 binding to exiv2, wrapped with Boost.Python.

**Comment by estribiyo** [comment]
Well, since [pyexiv2](https://launchpad.net/pyexiv2) where installed via pip:

```
pip install pyexiv2
```

After trying py3exiv2, that it's very difficult to compile under Windows and other library alternatives like a combination of iptcinfo3, exif, libxmp, ... (that have problems with GPS points). Seeing that your library it's using the original library name, I suposed that yours was a sucessor of pyexiv2... but looking the documentation I see that is an implementation that has nothing to do with the original one.

**Comment by estribiyo** [comment]
Currently I'm recoding my software to use your library.

I hope all issues with other libraries above mentioned are working... (gps, exif thumbnail, ...).

At the moment I confirm you that installation on Python 3.9 and Windows 10 is easy (fo further steps or external compilations) and works fine.

Thank you!

**Comment by estribiyo** [comment]
I know... in fact, the main problem with py3exiv2 is `exiv2.dll`, it's not packaged with the library... and their compilation under Windows is a pain in the ass. Besides, the author seems to have the project half abandoned, or doesn't care if it works on Windows or Mac... only compiles on Linux or must modify the `setup.py` to adapt it to this platforms.

Python End Of Life was 01 Jan 2020, CentOS is a little behind... :D

I've tested GPS and some basic functionalities... it seems to work pretty good. Thank you for your work.
