### ISSUE TITLE
EXIF embedded image

### ISSUE THREAD

**Issue by estribiyo** [LeoHsiao1/pyexiv2#98]
Is there any way to get/put embedded thumbnail image from/to APP1?

**Comment by LeoHsiao1** [comment]
I didn't have a need to use thumbnails before, so I didn't implement the API.
I can finish it at the weekend.

**Comment by LeoHsiao1** [comment]
I did some research on that.
Exiv2 supports reading and inserting thumbnails in IPEG images. But it's not a universal feature.
1. When Exif thumbnails are extracted from JPEG images, they can only be saved to disk :
  [thumbPath = newFilePath(path, "-thumb.jpg")](https://github.com/Exiv2/exiv2/blob/75f54e093fc03841a6bc42fb7a68ddc51ce9a81e/app/actions.cpp#L1082)
2. Only JPEG thumbnails can be inserted (not TIFF thumbnails), and must be named `path-thumb.jpg`.
3. The method eraseThumbnail() can be used directly.

Do you still want this feature?

**Comment by LeoHsiao1** [comment]
Never mind, I found a lower level API that can read and write thumbnails as a byte stream.

**Comment by LeoHsiao1** [comment]
I released [v2.8.0](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.8.0)

**Comment by estribiyo** [comment]
Many thanks!
