### ISSUE TITLE
Deleting custom attribute

### ISSUE THREAD

**Issue by MosGeo** [LeoHsiao1/pyexiv2#99]
I was wondering if it is possible to delete one or more custom attributes in xmp. I see that right now, we can clear the xmp. I don't know if this is technically feasible or not.

**Comment by LeoHsiao1** [comment]
According to the [tutorial](https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md#modify), you can assign None to remove a tag:
```py
img.modify_xmp({'Xmp.xmp.Rating': None})
```

**Comment by MosGeo** [comment]
Ahh perfect. Sorry for noticing that. So it actually removes the key :) Nice!

 I was actually doing that (thinking it is a good a substitute for removing the key). In my retrieval function, I am forcing to return None if the key is not there so I didn't notice that it was actually removed.
